name: build-ubuntu-20.04-backwards-compatibility
on:
  workflow_call:

env:
  CXX: g++
  SCCACHE_BUCKET: tiledb-ci-cache
  SCCACHE_ENDPOINT: ${{ secrets.R2_S3_ENDPOINT }}
  SCCACHE_S3_KEY_PREFIX: tiledb-core/sccache/
  VCPKG_BINARY_SOURCES: 'clear;x-aws,s3://tiledb-ci-cache/tiledb-core/vcpkg/,readwrite'

jobs:
  build:
    runs-on: ${{matrix.os}}
    if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    timeout-minutes: 120
    name: Build tiledb_unit
    steps:
      - name: Checkout TileDB
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS CLI
        run: ./scripts/ci/configure-aws-cli.py
        env:
          R2_S3_ENDPOINT: ${{ secrets.R2_S3_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Print Env
        run: ./scripts/ci/posix/print-env.sh
        shell: bash

      # Need this for virtualenv and arrow tests if enabled
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install pip and virtualenv
        run: |
          set -e pipefail
          python -m pip install --upgrade pip virtualenv
        shell: bash

      - name: Configure TileDB
        id: build
        shell: bash
        run: |
          bootstrap_args="${bootstrap_args}";
          bootstrap_args="${bootstrap_args} --enable-vcpkg --enable-ccache --enable-release-symbols";
          source $GITHUB_WORKSPACE/scripts/ci/bootstrap_libtiledb.sh

      - name: Build TileDB
        shell: bash
        run: |
          source $GITHUB_WORKSPACE/scripts/ci/build_libtiledb.sh

      # Save the tiledb_unit binary for use in the next step
      - name: Upload tiledb_unit
        uses: actions/upload-artifact@v3
        with:
          name: tiledb_unit
          path: ${{ github.workspace }}/build/tiledb/test/tiledb_unit
          retention-days: 1

  test:
    needs: build
    runs-on: ${{matrix.os}}
    if: ${{ startsWith(github.ref , 'refs/tags') != true && startsWith(github.ref , 'build-') != true }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        # Note: v2_1_0 arrays were never created so its currently skipped
        # Note: This matrix is used to set the value of TILEDB_COMPATIBILITY_VERSION
        tiledb_version:
          - "v1_4_0"
          - "v1_5_0"
          - "v1_6_0"
          - "v1_7_0"
          - "v2_0_0"
          - "v2_2_0"
          - "v2_2_3"
          - "v2_3_0"
          - "v2_4_0"
          - "v2_5_0"
          - "v2_6_0"
          - "v2_7_0"
          - "v2_8_3"
          - "v2_9_1"
          - "v2_10_0"
          - "v2_11_0"
          - "v2_12_0"
          - "v2_13_0"
          - "v2_14_0"
          - "v2_15_0"
          - "v2_16_0"
    timeout-minutes: 30
    name: ${{ matrix.tiledb_version }}
    steps:
      - name: Checkout TileDB
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Download tiledb_unit
        uses: actions/download-artifact@v3
        with:
          name: tiledb_unit
          path: ${{ github.workspace }}/build/tiledb/test/

      - name: Update tiledb_unit Permissions
        run: chmod +x $GITHUB_WORKSPACE/build/tiledb/test/tiledb_unit

      - name: Run Tests
        id: test
        env:
          TILEDB_COMPATIBILITY_VERSION: ${{ matrix.tiledb_version }}
        run: |
          ulimit -c unlimited
          ulimit -c

          cd $GITHUB_WORKSPACE

          # we clone the latest version, because we are specifying the
          # test target version in the TILEDB_COMPATIBILITY_VERSION variable
          git clone --depth=1 https://github.com/TileDB-Inc/TileDB-Unit-Test-Arrays.git --branch main test/inputs/arrays/read_compatibility_test

          # Remove all arrays besides the current matrix version
          ls test/inputs/arrays/read_compatibility_test/ | grep -v ${TILEDB_COMPATIBILITY_VERSION} | grep -v "__tiledb_group.tdb" | xargs -I{} echo "rm -r test/inputs/arrays/read_compatibility_test/{}"
          ls test/inputs/arrays/read_compatibility_test/ | grep -v ${TILEDB_COMPATIBILITY_VERSION} | grep -v "__tiledb_group.tdb" | xargs -I{} rm -r test/inputs/arrays/read_compatibility_test/{}
          rm -r test/inputs/arrays/read_compatibility_test/.git
          rm test/inputs/arrays/read_compatibility_test/.gitignore
          ls -lah test/inputs/arrays/read_compatibility_test/
          ls -lah test/inputs/arrays/read_compatibility_test/${TILEDB_COMPATIBILITY_VERSION}/

          # Bypass Catch2 Framework stdout interception with awk on test output
          $GITHUB_WORKSPACE/build/tiledb/test/tiledb_unit -d yes "[backwards-compat]"| awk '/1: ::set-output/{sub(/.*1: /, ""); print; next} 1'

      - name: Check Test Status
        run: |
          # tiledb_unit is configured to set a job-level variable TILEDB_CI_SUCCESS=1
          # following the test run. If this variable is not set, the build should fail.
          # see https://github.com/TileDB-Inc/TileDB/pull/1400 (5f0623f4d3)
          if [[ "${{ steps.test.outputs.TILEDB_CI_SUCCESS }}" -ne 1 ]]; then
            exit 1;
          fi

      - name: Print Log Files On Failed Builds
        run: |
          cd $GITHUB_WORKSPACE/build
          for f in $(find . -name *.log); do
            echo "::group::$f"
            cat $f
            echo "::endgroup::"
          done
        if: ${{ failure() }} # only run this job if the build step failed
