name: unit-test-standalone
on:
  workflow_call:

env:
  BACKWARDS_COMPATIBILITY_ARRAYS: OFF
  TILEDB_ASSERTIONS: ON
  TILEDB_S3: OFF
  TILEDB_AZURE: OFF
  TILEDB_GCS: OFF
  TILEDB_SERIALIZATION: ON
  TILEDB_STATIC: ON
  TILEDB_TOOLS: ON
  SCCACHE_BUCKET: tiledb-ci-cache
  SCCACHE_ENDPOINT: ${{ secrets.R2_S3_ENDPOINT }}
  SCCACHE_S3_KEY_PREFIX: tiledb-core/sccache/
  VCPKG_BINARY_SOURCES: 'clear;x-aws,s3://tiledb-ci-cache/tiledb-core/vcpkg/,readwrite'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    name: Build - ${{ matrix.os }}
    steps:
      - name: Checkout TileDB
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure AWS CLI
        run: ./scripts/ci/configure-aws-cli.py
        env:
          R2_S3_ENDPOINT: ${{ secrets.R2_S3_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Setup Homebrew
        run: brew install pkg-config
        if: ${{ startsWith(matrix.os, 'macos-') == true }}

      - name: Configure TileDB
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cd $GITHUB_WORKSPACE/build

          cmake .. \
            -DTILEDB_VCPKG=ON \
            -DTILEDB_CCACHE=ON \
            -DTILEDB_AZURE=${TILEDB_AZURE}\
            -DTILEDB_GCS=${TILEDB_GCS} \
            -DTILEDB_S3=${TILEDB_S3} \
            -DTILEDB_SERIALIZATION=${TILEDB_SERIALIZATION} \
            -DTILEDB_ASSERTIONS=${TILEDB_ASSERTIONS} \
            -DTILEDB_STATIC=${TILEDB_STATIC}

      - name: Build TileDB
        run: |
          cd $GITHUB_WORKSPACE/build
          make -j4

      - name: Build Tests
        run: |
          cd $GITHUB_WORKSPACE/build
          make -C tiledb -j4 tests

      - name: Run Tests
        id: test
        run: |
          cd $GITHUB_WORKSPACE/build
          make -C tiledb test ARGS="-R '^unit_'" -R "test_assert"
          make -C tiledb test ARGS="-R 'test_ci_asserts'"

      - name: Print Log Files On Failed Builds
        run: |
          cd $GITHUB_WORKSPACE
          for f in $(find . -name "*.log"); do
            echo "::group::$f"
            cat $f
            echo "::endgroup::"
          done
        if: ${{ failure() }} # only run this job if the build step failed
