name: unit-test-standalone
on:
  workflow_call:

env:
  BACKWARDS_COMPATIBILITY_ARRAYS: OFF
  TILEDB_ASSERTIONS: ON
  TILEDB_S3: OFF
  TILEDB_AZURE: OFF
  TILEDB_GCS: OFF
  TILEDB_SERIALIZATION: ON
  TILEDB_STATIC: ON
  TILEDB_TOOLS: ON
  SCCACHE_BUCKET: tiledb-ci-cache
  SCCACHE_ENDPOINT: ${{ secrets.R2_S3_ENDPOINT }}
  SCCACHE_S3_KEY_PREFIX: tiledb-core/sccache/
  VCPKG_BINARY_SOURCES: 'clear;x-aws,s3://tiledb-ci-cache/tiledb-core/vcpkg/,readwrite'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
      fail-fast: false
    name: Build - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: ./scripts/ci/configure-aws-cli.py
        env:
          R2_S3_ENDPOINT: ${{ secrets.R2_S3_ENDPOINT }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: 'Homebrew setup'
        run: brew install pkg-config
        if: ${{ startsWith(matrix.os, 'macos-') == true }}

      - name: 'Print env'
        run: |
          echo "'uname -s' is:"
          echo "uname: " $(uname)
          echo "uname -m: " $(uname -m)
          echo "uname -r:" $(uname -r)
          echo "uname -s: " $(uname -s)
          echo "uname -v: " $(uname -v)
          printenv
        shell: bash

      - name: 'Build and run standalone unit tests'
        id: test
        run: |

          mkdir -p $GITHUB_WORKSPACE/build
          pushd $GITHUB_WORKSPACE/build

          cmake .. \
            -DTILEDB_VCPKG=ON \
            -DTILEDB_CCACHE=ON \
            -DTILEDB_AZURE=${TILEDB_AZURE}\
            -DTILEDB_GCS=${TILEDB_GCS} \
            -DTILEDB_S3=${TILEDB_S3} \
            -DTILEDB_SERIALIZATION=${TILEDB_SERIALIZATION} \
            -DTILEDB_ASSERTIONS=${TILEDB_ASSERTIONS} \
            -DTILEDB_STATIC=${TILEDB_STATIC}
          make -j4
          # Build all unit tests
          make -C tiledb tests -j4
          # Run all unit tests
          make -C tiledb test ARGS="-R '^unit_'" -R "test_assert"
          make -C tiledb test ARGS="-R 'test_ci_asserts'"

          popd
      - name: "Print log files (failed build only)"
        run: |
          source $GITHUB_WORKSPACE/scripts/ci/print_logs.sh
        if: ${{ failure() }} # only run this job if the build step failed
